### ISSUE TITLE
Request to return compressed response for the request containing 'Accept-Encoding: gzip'

### ISSUE THREAD

**Issue by std4lqi** [zowe/data-sets#112]
I need download files using GET /api/v1/unixfiles/{path}. The file is usually 3~10 MB. It would be quite slow, if all bytes are transferred without compression.

I request to enhance the current API to return the compressed response with `Content-Encoding: gzip`, when the request header contains ` Accept-Encoding: gzip, deflate, br`. 

Thanks!

**Comment by jordanCain** [comment]
I can't see any reference to the ability to request a compressed format in the z/OSMF documentation (https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_GetReadUnixFile.htm) this would mean that any implementation we did for the data-set api would still first require a "slow/uncompressed" local fetch to z/OSMF before compressing in the data-sets api runtime for the external request. 

I will talk to the z/OSMF team to see if they have any plans or history on compressed responses.

**Comment by NakulManchanda** [comment]
Filed an RFE to z/OSMF team 
https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=138354

**Comment by NakulManchanda** [comment]
We have enabled gzip compression for both jobs-api and files-api on our end, seeing significant improve in load time around 50%.

There are three PR open to add this feature:
https://github.com/zowe/api-layer/pull/463 - needs somebody from API/ML team to vet this new config 

https://github.com/zowe/data-sets/pull/139
https://github.com/zowe/jobs/pull/83

**Comment by NakulManchanda** [comment]
Without compression:
Fetch and refresh same file 4 times
![image](https://user-images.githubusercontent.com/4791635/71421824-4decf900-264b-11ea-9c8d-3d8685ea723f.png)

With Compression enabled:
![image](https://user-images.githubusercontent.com/4791635/71421863-92789480-264b-11ea-9ec5-e704a5baebf7.png)

because of load times performance gains, we can make compression "true" by default, but user would be able to change this by modifying start.sh of respective service, by turning off
-Dserver.compression.enabled=false

**Comment by NakulManchanda** [comment]
all the PR related to this issue is merged. @nkocsis  @std4lqi
