### ISSUE TITLE
USS GET does not always convert correctly

### ISSUE THREAD

**Issue by phaumer** [zowe/data-sets#78]
**Describe the bug**
A REST API client that receives results as JSON can assume that all content has been converted to UTF-8 as specified for JSON in https://tools.ietf.org/html/rfc7159#section-8.1.
If a file is already in UTF-8 on the host it seems to be wrongly assume to be EBCDIC and converts it into some garbled content.  The REST server must recognize the format of the file and convert correctly.

**To Reproduce**
1. Request a file content of a UTF-8 file

**Expected behavior**
If the file is already in UTF do not convert. If in EBCDIC convert

**Comment by stevenhorsman** [comment]
I think we might need to break this down into 2 sub-stories
- Add the option to set the content type to binary rather than text. This can be implemented against z/OS MF rest API with the X-IBM-Data-Type: binary header. I'm not sure what the design of this should be
- Create a smarter system that uses chtag (https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_PutUnixFileUtilities.htm) to try and work out the code page type and then use this to work out whether to get the content in text, or binary mode. This is a better solution, but is more involved and needs more investigation into code pages, so will take much longer.

**Comment by jordanCain** [comment]
I'm closing this issue as I have raised the following two to track
Enhance get USS file contents by interrogating file tag property to set transfer mode #81
Enhance USS get file contents by providing an option to configure the transfer mode #82
